Corrected the typo I made for gf180mcuC in the gf180mcu/Makefile.in which caused a regression failure in the CI (error found and corrected by Claude Opus 5.5).  Also:  Because the typo caused an error that could not be seen in the log files, the Makefile.in was additionally changed to cause a failure on such errors with an output line that pinpoints the error, which should avoid a lot of hassle in trying to track down such simple problems in the future.  That change was made to both the sky130 and gf180mcu Makefiles.
Also:  Updated some of the documentation to reflect the change from
opencircuitdesign.com to the fossi-foundation github account, and the
name change from "open_pdks" to "open-pdks".

Also:  One error was encountered when attempting to run "make install"
overwriting an existing installation because of a change in an underlying
library which turned a directory name into a symbolic link to a different
name.  The install script now detects and resolves such problems instead
of exiting with an error code.

Signed-off-by: R. Timothy Edwards <tim@opencircuitdesign.com>

diff --git a/gf180mcu/Makefile.in b/gf180mcu/Makefile.in
--- a/gf180mcu/Makefile.in
+++ b/gf180mcu/Makefile.in
@@ -772,9 +772,16 @@ update-ocd-sc-repo:
 
 all-%: prerequisites
 	echo "Starting gf180mcu$* PDK staging on "`date` > ${GF180MCU$*}_make.log
-	${MAKE} general-$*
-	${MAKE} tools-$*
-	${MAKE} vendor-$*
+	# Run each stage in turn.  Copy each sub-make's stderr (which is where
+	# make reports its own errors) to the log, and on failure write an
+	# error line to the log and stop.
+	for stage in general tools vendor ; do \
+		${MAKE} $${stage}-$* 2> >(tee -a ${GF180MCU$*}_make.log >&2) || { \
+			echo "*** ERROR: 'make $${stage}-$*' failed; gf180mcu$* PDK staging aborted on "`date` | \
+				tee -a ${GF180MCU$*}_make.log >&2 ; \
+			exit 1 ; \
+		} ; \
+	done
 	echo "Ended gf180mcu$* PDK staging on "`date` >> ${GF180MCU$*}_make.log
 
 general-%: ${TECH}.json
@@ -988,7 +995,7 @@ vendor-A: primitive-build-A digital-7t5v0-build-A digital-9t5v0-build-A io-build
 
 vendor-B: primitive-build-B digital-7t5v0-build-B digital-9t5v0-build-B io-build-B ocd-io-build-B ocd-alpha-build-B sram-build-B ocd-sram-build-B digital-osu-build-B digital-ocd-build-B digital-avalon-build-B digital-efuse-build-B
 
-vendor-C: primitive-build-C digital-7t5v0-build-C digital-9t5v0-build-C io-build-C ocd-io-build-C ocd-alpha-build-C sram-build-C ocd-sram-build-C digital-osu-build-C digital-ocd_build-C digital-avalon-build-C digital-efuse-build-C
+vendor-C: primitive-build-C digital-7t5v0-build-C digital-9t5v0-build-C io-build-C ocd-io-build-C ocd-alpha-build-C sram-build-C ocd-sram-build-C digital-osu-build-C digital-ocd-build-C digital-avalon-build-C digital-efuse-build-C
 
 vendor-D: primitive-build-D digital-7t5v0-build-D digital-9t5v0-build-D io-build-D ocd-io-build-D ocd-alpha-build-D sram-build-D ocd-sram-build-D digital-osu-build-D digital-ocd-build-D digital-avalon-build-D digital-efuse-build-D
 
diff --git a/sky130/Makefile.in b/sky130/Makefile.in
--- a/sky130/Makefile.in
+++ b/sky130/Makefile.in
@@ -1001,9 +1001,14 @@ update-osu-t18-repo:
 
 all-%: prerequisites
 	echo "Starting sky130$* PDK staging on "`date` > ${SKY130$*}_make.log
-	${MAKE} general-$*
-	${MAKE} tools-$*
-	${MAKE} vendor-$*
+	# Run each stage in turn, reporting any fatal errors.
+	for stage in general tools vendor ; do \
+		${MAKE} $${stage}-$* 2> >(tee -a ${SKY130$*}_make.log >&2) || { \
+			echo "*** ERROR: 'make $${stage}-$*' failed; sky130$* PDK staging aborted on "`date` | \
+			tee -a ${SKY130$*}_make.log >&2 ; \
+			exit 1 ; \
+		} ; \
+	done
 	echo "Ended sky130$* PDK staging on "`date` >> ${SKY130$*}_make.log
 
 general-%: ${TECH}.json
